### PR TITLE
Pull request 1

### PR DESCRIPTION
**Pull request by jmckinstry**
Changes:
- Look and naming (tried to unify things a bit)
- .gitignore for ignoring files we don't want to track
- Moved APPLICATION_ID to somewhere that could be made safe for Github without making life harder
- Fixed the bug with showing the wrong play state when loading FB2K
- Fixed the bug where tracks with really long titles would cause janky behavior
- Added unencumbered images if folks didn't want to make their own
- Added DEBUG_CONSOLE_PRINTF calls for debugging
- Removed rate limiting that was already handled in Discord's library code
- Removed UnicodeToAnsi as it was unused
- Uhhhhh, accidentally listened to VS 2017 when it said I should change line return style because they were interchanged. Sorry

and made a release for FB2K 1.4.

Thanks for sharing your code with everybody! It was nice to have things mostly done before I got here. Do let me know if there's more you'd like changed, and pick and use whatever you want.

(and let me know if I did this wrong, first real pull request)

### CODE REVIEW

**Comment by NotTsunami** [comment]
Was it intentional to make the images opaque?

Otherwise, lgtm

**Comment by ultrasn0w** [comment]
Thanks for the PR, going to merge it.
Can you also provide a compiled build?
I no longer have a build environment set up.
`380156913989582850`

**Comment by jmckinstry** [comment]
> Was it intentional to make the images opaque?
> 
> Otherwise, lgtm

It was not intentional, but it doesn't seem to have harmed anything or reduced image quality in Discord, so I'll leave it as is.

> Thanks for the PR, going to merge it.
> Can you also provide a compiled build?
> I no longer have a build environment set up.
> `380156913989582850`

Thanks for the merge! Latest release at https://github.com/jmckinstry/foo_drpc/releases has the resulting dll, seems I can't attach it directly to this reply.

**Comment by ultrasn0w** [comment]
Thank you.
Did you compile it using the provided Aplication ID above?
If not I can't use it as a provided release here.

**Comment by jmckinstry** [comment]
Ah, I had misunderstood what that ID was (thought it was an automatic branch merge ID or something). Built, verified, attached. Let me know if you need more!

[foo_drpc.zip](https://github.com/ultrasn0w/foo_drpc/files/2542814/foo_drpc.zip)

**Pull request merged**
